phrase:
  access_token: 9664a9714eddb94f1a73f910a7e8a353695893676b49e7babce227669fc66f88
  project_id: eae8605abd55ee70612e421aa9176137
  push:
    sources:
      - file: ./src/utility/<locale_name>.json
        params:
          file_format: simple_json
          update_translations: true
  pull:
    targets:
      - file: ./src/utility/<locale_name>.json
        params:
          file_format: simple_json


